name: Auto Draw Crop Circles
on:
  # push:
  #   branches:
  #     - master
  # workflow_dispatch:
  #   branches:
  #     - master
  # 每 20 分钟执行一次
  schedule:
    - cron:  '0/5 * * * *'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: draw crop circles
      run: |-
        python main.py -logo ${{ secrets.LOGO }}

    - name: commit and push
      run: |-
        git diff
        git config --global user.email 289065406@qq.com
        git config --global user.name lyy289065406
        git config --global github.token ${{ secrets.GITHUB_TOKEN }}
        git add -A
        git commit -m "Updated by Github Robot" || exit 0
        git push

        
        

